### ISSUE TITLE
windows support

### ISSUE THREAD

**Issue by ghost** [zet4/alpine-tor#12]
Hello there.
At first, i must appreciate the work you have done here, it is amazing.
Second, i just wanted to know, putting aside the HAproxy solution, is it possible to extend your scenario on windows machine as well? btw: the privoxy idea is really brilliant because it opens a layer of interception for the developer, nice work.
thanks in advance.

**Comment by zet4** [comment]
I am not 100% sure what you mean but last I checked you can run this as a linux container in docker for windows and just expose ports to whatever you need from there.

**Comment by ghost** [comment]
well done. i appreciate your kind and helpful answer, this is amazing.
