### ISSUE TITLE
Explicitly set ExitPolicy and make configurable

### ISSUE THREAD

**Issue by tmiklas** [zet4/alpine-tor#4]
How about adding explicit ExitPolicy to tor start command? At present running this containers makes you a Tor exit node which is undesired by most. I suggest it should be configurable with default set to reject, i.e. `--ExitPolicy "reject *:*"` in command line.

**Comment by zet4** [comment]
Sorry, my hands are currently full with work so while this seems like a nice idea, I am not able to do it myself right now, but, feel free to open a PR and I will take a look at it.
