### ISSUE TITLE
500 Internal Privoxy Error when Privoxy enabled

### ISSUE THREAD

**Issue by arturhg** [zet4/alpine-tor#8]
When Privoxy enabled sometimes this error appears as a response:

<h1>500 Internal Privoxy Error</h1>
<p>Privoxy encountered an error while processing your request:</p>
<p><strong>Could not load template file <code>no-server-data</code> or one of its included components.</strong></p>
<p>Please contact your proxy administrator.</p>
<p>If you are the proxy administrator, please put the required file(s)in the <code><em>(confdir)</em>/templates</code> directory. The location of the <code><em>(confdir)</em></code> directory is specified in the main Privoxy <code>config</code> file. (It's typically the Privoxy install directory, or <code>/etc/privoxy/</code>).</p>

Steps to reproduce:

1. `docker run -d -p 8118:8118 -p 2090:2090 -e tors=25 -e privoxy=1 zeta0/alpine-tor`
2. Make a request with HTTP proxy
3. Get error

**Comment by Otetz** [comment]
Agreed, sometimes this happen. 
I have workaround for python `requests`: https://github.com/Otetz/requests_proxy_adapter

**Comment by arturhg** [comment]
@Otetz This is great!
But for fixing problem from the root, we can remove privoxy and use [DeleGate](http://www.delegate.org/) instead.
Like this: DeleGate -> HaProxy -> Tors
Or there is a better solution?

**Comment by zet4** [comment]
#7 mostly covers this so I will close this for now
